'use client';

import React, { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import {
  Dialog,
  DialogContent,
  DialogActions,
  Button,
  TextField,
  Box,
  Typography,
  Stack,
  IconButton,
  Collapse,
  useTheme,
  useMediaQuery,
  FormControlLabel,
  Checkbox,
  Fade,
} from '@mui/material';
import {
  Close as CloseIcon,
  Delete as DeleteIcon,
} from '@mui/icons-material';
import { useAuth } from '../../lib/context/userContext';
import { useCustomTheme } from '../../lib/context/themeContext';
import { SchedulesProps } from '../../lib/interface';

interface SchedulesModalProps {
  open: boolean;
  onClose: () => void;
  schedule?: SchedulesProps | null;
  selectedDate: string;
  onSave: (schedule: SchedulesProps) => void;
  onDelete?: (scheduleId: string) => void;
  onDateChange?: (date: string) => void;
  existingSchedules?: SchedulesProps[];
}

const SchedulesModal: React.FC<SchedulesModalProps> = ({
  open,
  onClose,
  schedule,
  selectedDate,
  onSave,
  onDelete,
  onDateChange,
  existingSchedules = [],
}) => {
  const { user } = useAuth();
  const { theme } = useCustomTheme();
  const muiTheme = useTheme();
  const isMobile = useMediaQuery(muiTheme.breakpoints.down('sm'));

  const [userHasEditedTimes, setUserHasEditedTimes] = useState(false);

  // Helper to suggest next start time
  const suggestNextStartTime = useCallback((existing: SchedulesProps[]) => {
    const timedSchedules = existing.filter(s => !s.isFlexible && s.startTime);
    if (timedSchedules.length === 0) {
      const now = new Date();
      const nextHour = new Date(now.getTime() + 60 * 60 * 1000);
      nextHour.setMinutes(0);
      const start = `${String(nextHour.getHours()).padStart(2, '0')}:00`;
      const end = `${String((nextHour.getHours() + 1) % 24).padStart(2, '0')}:00`;
      return { startTime: start, endTime: end };
    }

    const sorted = [...timedSchedules].sort((a, b) => a.startTime.localeCompare(b.startTime));
    const last = sorted[sorted.length - 1];
    const start = last.endTime || last.startTime;
    
    const duration = last.duration || 30;
    const [h, m] = start.split(':').map(Number);
    const endDate = new Date();
    endDate.setHours(h, m + duration);
    const end = `${String(endDate.getHours()).padStart(2, '0')}:${String(endDate.getMinutes()).padStart(2, '0')}`;
    
    return { startTime: start, endTime: end };
  }, []);



  //   const hours = now.getHours().toString().padStart(2, '0');
  //   const minutes = now.getMinutes().toString().padStart(2, '0');
  //   return `${hours}:${minutes}`;
  // };

  const [formData, setFormData] = useState<Partial<SchedulesProps>>({
    title: '',
    startTime: '',
    endTime: '',
    objective: '',
    duration: 0,
    status: 'pending',
    priority: 'medium',
    reminder: {
      before: 10,
      method: 'notification',
    },
    repeat: 'none',
    autoGenerated: false,
    colorCode: '#E3F2FD',
    isFlexible: false,
  });

  const timeConflict = useMemo(() => {
    if (formData.isFlexible || !formData.startTime) return false;
    const start = formData.startTime;
    
    let end = formData.endTime;
    if (!end) {
      const [h, m] = start.split(':').map(Number);
      const date = new Date();
      date.setHours(h, m + 30);
      end = `${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`;
    }

    return existingSchedules.some((s) => {
      if (s.isFlexible || s.id === schedule?.id) return false;
      const sStart = s.startTime;
      const sEnd = s.endTime || s.startTime;
      return start < sEnd && sStart < end;
    });
  }, [formData.startTime, formData.endTime, formData.isFlexible, existingSchedules, schedule]);

  const titleInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (open) {
      // Small delay to ensure Dialog transition is underway and focus trap is ready
      const timer = setTimeout(() => {
        if (titleInputRef.current) {
          titleInputRef.current.focus();
        }
      }, 100);
      return () => clearTimeout(timer);
    }
  }, [open]);

  const handleQuickDate = (
    type: 'tomorrow' | 'afterTomorrow' | 'endOfWeek',
  ) => {
    const date = new Date();
    if (type === 'tomorrow') {
      date.setDate(date.getDate() + 1);
    } else if (type === 'afterTomorrow') {
      date.setDate(date.getDate() + 2);
    } else if (type === 'endOfWeek') {
      const day = date.getDay();
      const diff = day === 0 ? 7 : 7 - day;
      date.setDate(date.getDate() + diff);
    }

    const yyyy = date.getFullYear();
    const mm = String(date.getMonth() + 1).padStart(2, '0');
    const dd = String(date.getDate()).padStart(2, '0');
    const formattedDate = `${yyyy}-${mm}-${dd}`;

    if (onDateChange) {
      onDateChange(formattedDate);
    }
  };


  const dynamicQuickTimes = useMemo(() => {
    const now = new Date();
    const today = now.toISOString().split('T')[0];

    // For future dates, show standard slots
    if (selectedDate !== today) return ['09:00', '13:00', '17:00', '21:00'];

    const currentHour = now.getHours();
    let offsets: number[] = [];

    if (currentHour <= 14) {
      // First two: 1h distance | Next two: 2h distance
      // e.g. at 14:00 (2 PM) -> 15:00, 16:00, 18:00, 20:00
      offsets = [1, 2, 4, 6];
    } else {
      // Distance each 1 hour
      // e.g. at 15:00 (3 PM) -> 16:00, 17:00, 18:00, 19:00
      offsets = [1, 2, 3, 4];
    }

    return offsets
      .map((offset) => currentHour + offset)
      .filter((h) => h < 24)
      .map((h) => `${String(h).padStart(2, '0')}:00`);
  }, [selectedDate]);

  const applyDuration = (minutes: number) => {
    if (!formData.startTime) return;
    const [h, m] = formData.startTime.split(':').map(Number);
    const date = new Date();
    date.setHours(h, m + minutes);
    const endH = String(date.getHours()).padStart(2, '0');
    const endM = String(date.getMinutes()).padStart(2, '0');
    const newEndTime = `${endH}:${endM}`;
    handleInputChange('endTime', newEndTime);
    handleDurationChange(formData.startTime, newEndTime);
  };

  // Initialize form data when modal opens
  useEffect(() => {
    if (open) {
      setUserHasEditedTimes(false);
      if (schedule) {
        setFormData({
          title: schedule.title,
          startTime: schedule.startTime,
          endTime: schedule.endTime,
          objective: schedule.objective,
          duration: schedule.duration,
          status: schedule.status || 'pending',
          priority: schedule.priority,
          reminder: schedule.reminder,
          repeat: schedule.repeat,
          autoGenerated: schedule.autoGenerated,
          colorCode: schedule.colorCode,
          isFlexible: schedule.isFlexible || false,
        });
      } else {
        const suggestion = suggestNextStartTime(existingSchedules);
        setFormData({
          title: '',
          startTime: suggestion.startTime,
          endTime: suggestion.endTime,
          objective: '',
          duration: 30,
          status: 'pending',
          priority: 'medium',
          reminder: {
            before: 10,
            method: 'notification',
          },
          repeat: 'none',
          autoGenerated: false,
          colorCode: '#E3F2FD',
          isFlexible: false,
        });
      }
    }
  }, [open, schedule, existingSchedules, suggestNextStartTime]);

  // Re-suggest start/end times if date (existingSchedules) changes and user hasn't edited times
  useEffect(() => {
    if (open && !schedule && !userHasEditedTimes) {
      const suggestion = suggestNextStartTime(existingSchedules);
      setFormData((prev) => ({
        ...prev,
        startTime: suggestion.startTime,
        endTime: suggestion.endTime,
      }));
    }
  }, [existingSchedules, open, schedule, userHasEditedTimes, suggestNextStartTime]);

  const handleInputChange = (
    field: keyof SchedulesProps,
    value:
      | string
      | number
      | boolean
      | { before: number; method: string }
      | string[]
      | number[]
      | unknown,
  ) => {
    setFormData((prev) => ({
      ...prev,
      [field]: value,
    }));
  };

  const handleDurationChange = (startTime: string, endTime: string) => {
    if (startTime && endTime) {
      const [startHour, startMin] = startTime.split(':').map(Number);
      const [endHour, endMin] = endTime.split(':').map(Number);

      const startMinutes = startHour * 60 + startMin;
      const endMinutes = endHour * 60 + endMin;

      const duration = endMinutes - startMinutes;
      if (duration > 0) {
        setFormData((prev) => ({
          ...prev,
          duration,
        }));
      }
    }
  };

  const handleSave = () => {
    const isFlexible = formData.isFlexible || false;
    if (!user || !formData.title || (!isFlexible && !formData.startTime)) {
      console.error('Missing required fields:', {
        user: !!user,
        title: formData.title,
        startTime: formData.startTime,
        isFlexible,
      });
      return;
    }

    // If no end time provided, assume 30 minutes duration
    const startTime = formData.startTime || '00:00';
    let endTime = formData.endTime;
    if (!endTime && startTime) {
      const [hours, minutes] = formData.startTime.split(':').map(Number);
      const startMinutes = hours * 60 + minutes;
      const endMinutes = startMinutes + 30; // Default 30 minutes
      const endHours = Math.floor(endMinutes / 60);
      const endMins = endMinutes % 60;
      endTime = `${endHours.toString().padStart(2, '0')}:${endMins
        .toString()
        .padStart(2, '0')}`;
    }

    const hasReminder = false;
    const reminderDateVal: Date | null = null;

    const scheduleData: SchedulesProps = {
      ...(schedule?.id ? { id: schedule.id } : {}),
      userId: user.uid,
      date: isFlexible ? '' : selectedDate,
      title: formData.title,
      startTime: startTime,
      endTime: endTime || startTime,
      objective: formData.objective || '',
      duration: formData.duration || 30,
      status: formData.status || 'pending',
      priority: formData.priority || 'medium',
      reminder: {
        before: 10,
        method: 'notification',
      },
      hasReminder,
      reminderDate: reminderDateVal,
      repeat: 'none',
      autoGenerated: formData.autoGenerated || false,
      colorCode: formData.colorCode || '#E3F2FD',
      isFlexible: formData.isFlexible || false,
      frequencyMode: formData.frequencyMode || (formData.isFlexible ? 'daily' : undefined),
      selectedDaysOfWeek: formData.selectedDaysOfWeek || [],
      selectedDaysOfMonth: formData.selectedDaysOfMonth || [],
      linkedGoalId: schedule?.linkedGoalId || formData.linkedGoalId || null,
      goalTitle: schedule?.goalTitle || formData.goalTitle,
      goalRole: schedule?.goalRole || formData.goalRole,
      contributionAmount: schedule?.contributionAmount || formData.contributionAmount,
      contributionUnit: schedule?.contributionUnit || formData.contributionUnit,
      createdAt: schedule?.createdAt || new Date(),
      updatedAt: new Date(),
    };

    console.log('Saving schedule data:', scheduleData);
    onSave(scheduleData);
    onClose();
  };

  const handleDelete = () => {
    if (schedule?.id && onDelete) {
      onDelete(schedule.id);
      onClose();
    }
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="sm"
      fullWidth
      fullScreen={isMobile}
      TransitionComponent={Fade}
      transitionDuration={400}
      PaperProps={{
        className: `rounded-[28px] overflow-hidden shadow-2xl border transition-all ${
          theme?.mode === 'dark'
            ? 'bg-slate-900 border-slate-800 text-slate-100'
            : 'bg-white border-slate-100 text-slate-850'
        }`,
        sx: { 
          borderRadius: '28px',
          backgroundColor: theme?.mode === 'dark' ? '#0f172a' : '#ffffff',
          color: theme?.mode === 'dark' ? '#f1f5f9' : '#0f172a',
        },
      }}
    >
      {/* Premium Gradient Header */}
      <Box className="p-6 bg-gradient-to-br from-violet-500 to-indigo-700 text-white flex justify-between items-center">
        <Box>
          <Typography variant="h6" className="font-extrabold">
            {schedule ? 'Edit Schedule' : 'Plan Your Day'}
          </Typography>
          <Typography variant="body2" className="opacity-90">
            {schedule
              ? 'Refine your session details'
              : 'Create a new productive session'}
          </Typography>
        </Box>
        <IconButton
          onClick={onClose}
          className="text-white hover:bg-white/20 transition-colors"
        >
          <CloseIcon />
        </IconButton>
      </Box>

      <DialogContent className="p-6">
        <Box className="flex flex-col gap-10 pt-4">
          {/* Title Input */}
          <Box>
            <Typography className="text-[11px] font-extrabold text-slate-400 dark:text-slate-500 uppercase tracking-[0.2em] mb-3 ml-1">
              🏷️ Title
            </Typography>
            <TextField
              inputRef={titleInputRef}
              fullWidth
              value={formData.title}
              onChange={(e) => handleInputChange('title', e.target.value)}
              required
              variant="outlined"
              placeholder="What's the focus?"
              sx={{
                '& .MuiOutlinedInput-root': {
                  borderRadius: '16px',
                  backgroundColor:
                    theme?.mode === 'dark' ? 'rgba(15, 23, 42, 0.5)' : '#fff',
                  fontSize: '1.15rem',
                  fontWeight: 700,
                  transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
                  '& fieldset': {
                    borderColor: theme?.mode === 'dark' ? '#334155' : '#e2e8f0',
                  },
                  '&:hover fieldset': { borderColor: '#8b5cf6' },
                  '&.Mui-focused fieldset': {
                    borderColor: '#8b5cf6',
                    borderWidth: '2px',
                  },
                  '&.Mui-focused': {
                    boxShadow: '0 0 0 4px rgba(139, 92, 246, 0.1)',
                  },
                },
              }}
            />
          </Box>

          {/* Status Checkbox (Edit Mode Only) */}
          {schedule && (
            <Box sx={{ mt: -2, mb: -1, ml: 1 }}>
              <FormControlLabel
                control={
                  <Checkbox
                    checked={formData.status === 'completed'}
                    onChange={(e) => handleInputChange('status', e.target.checked ? 'completed' : 'pending')}
                    sx={{
                      color: '#8b5cf6',
                      '&.Mui-checked': { color: '#8b5cf6' },
                    }}
                  />
                }
                label={
                  <Typography className="text-sm font-bold text-slate-800 dark:text-slate-200">
                    I have done it
                  </Typography>
                }
              />
            </Box>
          )}

          {/* Date / Deadline Section */}
          <Box className={`p-6 rounded-[24px] border transition-all ${
            theme?.mode === 'dark'
              ? 'bg-slate-900/30 border-slate-800'
              : 'bg-slate-50 border-slate-100'
          }`}>
            <Box className="flex items-center justify-between mb-4">
              <Typography className="text-[11px] font-extrabold text-violet-600 dark:text-violet-400 uppercase tracking-[0.2em]">
                📅 Schedule Date & Frequency
              </Typography>
            </Box>

            {/* Show me frequency selector */}
            <Box sx={{ mb: 2 }}>
              <Typography className="text-[10px] font-extrabold text-slate-400 dark:text-slate-500 uppercase tracking-wider mb-1.5 ml-1">
                Show me
              </Typography>
              <Stack direction="row" spacing={1} mb={1.5}>
                {[
                  { label: 'Daily', value: 'daily' },
                  { label: 'Once a week', value: 'weekly' },
                  { label: 'Once a month', value: 'monthly' },
                ].map((mode) => {
                  const active = (formData.frequencyMode || (formData.isFlexible ? 'daily' : 'daily')) === mode.value;
                  return (
                    <Button
                      key={mode.value}
                      size="small"
                      variant={active ? 'contained' : 'outlined'}
                      onClick={() => {
                        handleInputChange('frequencyMode', mode.value);
                        if (mode.value === 'daily') {
                          handleInputChange('isFlexible', true);
                        } else {
                          handleInputChange('isFlexible', false);
                        }
                      }}
                      sx={{
                        borderRadius: '999px',
                        textTransform: 'none',
                        fontWeight: 700,
                        fontSize: '11px',
                        px: 2,
                        py: 0.5,
                        bgcolor: active ? '#8b5cf6' : 'transparent',
                        borderColor: active ? '#8b5cf6' : theme?.mode === 'dark' ? '#334155' : '#cbd5e1',
                        color: active ? '#fff' : theme?.mode === 'dark' ? '#cbd5e1' : '#475569',
                      }}
                    >
                      {mode.label}
                    </Button>
                  );
                })}
              </Stack>

              {/* Weekly Day Chips (Mon-Sun) */}
              {formData.frequencyMode === 'weekly' && (
                <Box sx={{ mt: 1.5, p: 1.5, borderRadius: '14px', bgcolor: theme?.mode === 'dark' ? '#1e293b' : '#ffffff', border: `1px solid ${theme?.mode === 'dark' ? '#334155' : '#e2e8f0'}` }}>
                  <Typography className="text-[10px] font-bold text-slate-400 mb-1.5">
                    Select Days of the Week (Tap to choose):
                  </Typography>
                  <Stack direction="row" spacing={0.75} flexWrap="wrap" gap={0.5}>
                    {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((dayName, idx) => {
                      const selected = (formData.selectedDaysOfWeek || []).includes(idx);
                      return (
                        <Button
                          key={dayName}
                          size="small"
                          onClick={() => {
                            const prev = formData.selectedDaysOfWeek || [];
                            const updated = prev.includes(idx) ? prev.filter((d) => d !== idx) : [...prev, idx];
                            handleInputChange('selectedDaysOfWeek', updated);
                          }}
                          sx={{
                            minWidth: 36,
                            height: 32,
                            borderRadius: '8px',
                            fontWeight: 800,
                            fontSize: '11px',
                            bgcolor: selected ? '#8b5cf6' : theme?.mode === 'dark' ? '#0f172a' : '#f1f5f9',
                            color: selected ? '#fff' : theme?.mode === 'dark' ? '#94a3b8' : '#64748b',
                            border: `1px solid ${selected ? '#8b5cf6' : 'transparent'}`,
                          }}
                        >
                          {dayName}
                        </Button>
                      );
                    })}
                  </Stack>
                </Box>
              )}

              {/* Monthly Day Chips (1-31) */}
              {formData.frequencyMode === 'monthly' && (
                <Box sx={{ mt: 1.5, p: 1.5, borderRadius: '14px', bgcolor: theme?.mode === 'dark' ? '#1e293b' : '#ffffff', border: `1px solid ${theme?.mode === 'dark' ? '#334155' : '#e2e8f0'}` }}>
                  <Typography className="text-[10px] font-bold text-slate-400 mb-1.5">
                    Select Days of the Month (Tap to choose):
                  </Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" gap={0.5} sx={{ maxHeight: 120, overflowY: 'auto' }}>
                    {Array.from({ length: 31 }, (_, i) => i + 1).map((dayNum) => {
                      const selected = (formData.selectedDaysOfMonth || []).includes(dayNum);
                      return (
                        <Button
                          key={dayNum}
                          size="small"
                          onClick={() => {
                            const prev = formData.selectedDaysOfMonth || [];
                            const updated = prev.includes(dayNum) ? prev.filter((d) => d !== dayNum) : [...prev, dayNum];
                            handleInputChange('selectedDaysOfMonth', updated);
                          }}
                          sx={{
                            minWidth: 28,
                            height: 28,
                            borderRadius: '6px',
                            fontWeight: 800,
                            fontSize: '10px',
                            bgcolor: selected ? '#8b5cf6' : theme?.mode === 'dark' ? '#0f172a' : '#f1f5f9',
                            color: selected ? '#fff' : theme?.mode === 'dark' ? '#94a3b8' : '#64748b',
                            p: 0,
                          }}
                        >
                          {dayNum}
                        </Button>
                      );
                    })}
                  </Stack>
                </Box>
              )}
            </Box>

            <Collapse in={formData.frequencyMode !== 'daily' && !formData.isFlexible}>
              <Box>
                <TextField
                  type="date"
                  value={selectedDate}
                  onChange={(e) => onDateChange && onDateChange(e.target.value)}
                  fullWidth
                  sx={{
                    '& .MuiOutlinedInput-root': {
                      borderRadius: '16px',
                      backgroundColor:
                        theme?.mode === 'dark' ? '#1e3a8a20' : '#f0f7ff',
                      '& fieldset': {
                        borderColor: '#3b82f6',
                        borderWidth: '2px',
                      },
                    },
                    '& .MuiInputBase-input': {
                      textAlign: 'center',
                      fontWeight: 800,
                      color: '#2563eb',
                      fontSize: '1.1rem',
                      letterSpacing: '1px',
                    },
                  }}
                  helperText={
                    <Typography
                      variant="caption"
                      className="text-slate-400 dark:text-slate-500 font-bold ml-1 uppercase tracking-wider"
                    >
                      {new Date(selectedDate).toLocaleDateString('en-US', {
                        weekday: 'long',
                        month: 'long',
                        day: 'numeric',
                      })}
                    </Typography>
                  }
                />
                <Stack
                  direction="row"
                  spacing={1}
                  mt={2.5}
                  className="overflow-x-auto pb-1 no-scrollbar flex-nowrap"
                >
                  {[
                    { label: 'Tomorrow', value: 'tomorrow' },
                    { label: 'In 2 Days', value: 'afterTomorrow' },
                    { label: 'Weekend', value: 'endOfWeek' },
                  ].map((item) => (
                    <Button
                      key={item.value}
                      variant="outlined"
                      onClick={() =>
                        handleQuickDate(
                          item.value as
                          | 'tomorrow'
                          | 'afterTomorrow'
                          | 'endOfWeek',
                        )
                      }
                      className="rounded-full normal-case text-[12px] font-bold px-5 py-1.5 whitespace-nowrap border-slate-200 dark:border-slate-700 text-slate-500 dark:text-slate-400 hover:border-violet-400 hover:text-violet-500 hover:bg-violet-50 dark:hover:bg-violet-900/10 transition-all"
                    >
                      {item.label}
                    </Button>
                  ))}
                </Stack>
              </Box>
            </Collapse>
          </Box>

          {/* Time Selection */}
          <Box className="relative">
            <Typography className="text-[11px] font-extrabold text-slate-400 dark:text-slate-500 uppercase tracking-[0.2em] mb-3 ml-1">
              ⏰ Session Timing
            </Typography>

            <Box className={`p-4 rounded-[20px] border shadow-sm ${
              theme?.mode === 'dark'
                ? 'bg-slate-950/40 border-slate-800'
                : 'bg-white border-slate-100'
            }`}>
              <Stack
                direction={{ xs: 'column', sm: 'row' }}
                alignItems="center"
                spacing={2}
              >
                {/* Start Time Pill */}
                <Box className="flex-1 w-full">
                  <TextField
                    type="time"
                    value={formData.startTime}
                    onChange={(e) => {
                      handleInputChange('startTime', e.target.value);
                      setUserHasEditedTimes(true);
                      if (formData.endTime)
                        handleDurationChange(e.target.value, formData.endTime);
                    }}
                    fullWidth
                    InputLabelProps={{ shrink: true }}
                    InputProps={{
                      className: theme?.mode === 'dark'
                        ? 'bg-slate-800 text-slate-100 [color-scheme:dark]'
                        : 'bg-slate-50 text-slate-900 [color-scheme:light]',
                    }}
                    sx={{
                      '& .MuiOutlinedInput-root': {
                        borderRadius: '12px',
                        border: 'none',
                        '& fieldset': { border: 'none' },
                        height: '48px',
                        backgroundColor: theme?.mode === 'dark' ? '#1e293b' : '#f8fafc',
                      },
                      '& .MuiInputBase-input': {
                        fontWeight: 800,
                        textAlign: 'center',
                        fontSize: '1rem',
                        color: theme?.mode === 'dark' ? '#f1f5f9' : '#0f172a',
                      },
                    }}
                  />
                  <Box className="flex flex-wrap justify-center gap-1.5 mt-2">
                    {dynamicQuickTimes.slice(0, 3).map((time) => (
                      <Button
                        key={time}
                        onClick={() => {
                          handleInputChange('startTime', time);
                          setUserHasEditedTimes(true);
                        }}
                        className="min-w-0 px-2 py-0.5 text-[10px] font-bold rounded-full bg-slate-50 dark:bg-slate-800 text-slate-500 dark:text-slate-400 border border-slate-100 dark:border-slate-700 hover:bg-violet-500 hover:text-white transition-all"
                      >
                        {time}
                      </Button>
                    ))}
                  </Box>
                </Box>

                {/* Connection Arrow */}
                <Box className="hidden sm:block text-slate-300">
                  <Typography variant="h5">→</Typography>
                </Box>

                {/* End Time Pill */}
                <Box className="flex-1 w-full">
                  <TextField
                    type="time"
                    value={formData.endTime}
                    onChange={(e) => {
                      handleInputChange('endTime', e.target.value);
                      setUserHasEditedTimes(true);
                      if (formData.startTime)
                        handleDurationChange(
                          formData.startTime,
                          e.target.value,
                        );
                    }}
                    fullWidth
                    InputLabelProps={{ shrink: true }}
                    InputProps={{
                      className: theme?.mode === 'dark'
                        ? 'bg-slate-800 text-slate-100 [color-scheme:dark]'
                        : 'bg-slate-50 text-slate-900 [color-scheme:light]',
                    }}
                    sx={{
                      '& .MuiOutlinedInput-root': {
                        borderRadius: '12px',
                        border: 'none',
                        '& fieldset': { border: 'none' },
                        height: '48px',
                        backgroundColor: theme?.mode === 'dark' ? '#1e293b' : '#f8fafc',
                      },
                      '& .MuiInputBase-input': {
                        fontWeight: 800,
                        textAlign: 'center',
                        fontSize: '1rem',
                        color: theme?.mode === 'dark' ? '#f1f5f9' : '#0f172a',
                      },
                    }}
                  />
                  <Box className="flex flex-wrap justify-center gap-1.5 mt-2">
                    {[15, 30, 60].map((mins) => (
                      <Button
                        key={mins}
                        disabled={!formData.startTime}
                        onClick={() => {
                          applyDuration(mins);
                          setUserHasEditedTimes(true);
                        }}
                        className="min-w-0 px-2 py-0.5 text-[10px] font-bold rounded-full bg-slate-50 dark:bg-slate-800 text-slate-500 dark:text-slate-400 border border-slate-100 dark:border-slate-700 hover:bg-indigo-500 hover:text-white transition-all"
                      >
                        +{mins}m
                      </Button>
                    ))}
                  </Box>
                </Box>
              </Stack>

              {formData.duration ? (
                <Box className="mt-3 pt-3 border-t border-slate-50 dark:border-slate-800 text-center">
                  <Typography className="text-[10px] font-bold text-violet-500 dark:text-violet-400 uppercase tracking-widest">
                    ⏱️ Total: {formData.duration} Minutes
                  </Typography>
                </Box>
              ) : null}

              {timeConflict && (
                <Box className="mt-3 pt-3 border-t border-slate-50 dark:border-slate-800 text-center">
                  <Typography color="error" variant="caption" sx={{ fontWeight: 'bold' }}>
                    ⚠️ Conflict: This overlaps with another schedule on this day.
                  </Typography>
                </Box>
              )}
            </Box>
          </Box>

          {/* Objective */}
          <Box>
            <Typography className="text-[11px] font-extrabold text-slate-400 dark:text-slate-500 uppercase tracking-[0.2em] mb-3 ml-1">
              🎯 Objective
            </Typography>
            <TextField
              fullWidth
              value={formData.objective}
              onChange={(e) => handleInputChange('objective', e.target.value)}
              placeholder="What's the desired outcome?"
              variant="outlined"
              sx={{
                '& .MuiOutlinedInput-root': {
                  borderRadius: '16px',
                  backgroundColor:
                    theme?.mode === 'dark' ? 'rgba(15, 23, 42, 0.5)' : '#fff',
                  '&:hover fieldset': { borderColor: '#8b5cf6' },
                  '&.Mui-focused fieldset': { borderColor: '#8b5cf6' },
                },
              }}
              helperText={
                <span className="text-[11px] font-medium text-slate-400">
                  💡 A clear goal significantly improves focus
                </span>
              }
            />
          </Box>

          {/* Reminder Info Message Box */}
          <Box

            sx={{
              p: 2,
              borderRadius: '16px',
              border: `1px dashed ${theme?.mode === 'dark' ? '#334155' : '#cbd5e1'}`,
              bgcolor: theme?.mode === 'dark' ? 'rgba(30, 41, 59, 0.2)' : '#f8fafc',
              display: 'flex',
              alignItems: 'center',
              gap: 1.5,
            }}
          >
            <Typography
              variant="body2"
              sx={{
                fontSize: '13px',
                fontWeight: 600,
                color: theme?.mode === 'dark' ? '#94a3b8' : '#475569',
                textAlign: 'center',
                width: '100%',
              }}
            >
              {"📢 You can set reminder for notification after creating the schedule by clicking 'Notification' icon."}
            </Typography>
          </Box>
        </Box>
      </DialogContent>

      <DialogActions className={`p-6 border-t gap-2 ${
        theme?.mode === 'dark'
          ? 'bg-slate-950/20 border-slate-800'
          : 'bg-slate-50/50 border-slate-100'
      }`}>
        {schedule && onDelete && (
          <Button
            onClick={handleDelete}
            color="error"
            variant="outlined"
            className="rounded-xl border-2 font-bold px-6 py-2 normal-case mr-auto"
            startIcon={<DeleteIcon />}
          >
            <span className="hidden sm:inline">Delete</span>
          </Button>
        )}
        <Button
          onClick={onClose}
          variant="outlined"
          color="error"
          className="rounded-xl font-bold px-6 py-2 normal-case border border-red-500 text-red-500 hover:bg-red-50 dark:border-red-500/40 dark:text-red-400 dark:hover:bg-red-950/30 transition-all"
        >
          Cancel
        </Button>
        <Button
          onClick={handleSave}
          variant="contained"
          disabled={
            !formData.title || (!formData.isFlexible && !formData.startTime) || timeConflict
          }
          className="rounded-xl font-extrabold px-8 py-2 normal-case bg-gradient-to-r from-violet-600 to-indigo-600 shadow-lg shadow-indigo-500/30 hover:shadow-indigo-500/50"
        >
          {schedule ? 'Update Session' : 'Start Planning'}
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default SchedulesModal;
