'use client';

import React, { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import {
  Dialog,
  DialogContent,
  DialogActions,
  Button,
  TextField,
  Box,
  Typography,
  Stack,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  IconButton,
  Collapse,
  useTheme,
  useMediaQuery,
  Switch,
  FormControlLabel,
  Checkbox,
} from '@mui/material';
import {
  Close as CloseIcon,
  Delete as DeleteIcon,
  ExpandMore as ExpandMoreIcon,
  ExpandLess as ExpandLessIcon,
} from '@mui/icons-material';
import CustomWheelTimePicker from '@/app/test/time-picker/TimePicker';
import {
  DateRange as CustomDateIcon,
  WhatsApp as WhatsAppIcon,
  NotificationsActive as PushIcon,
} from '@mui/icons-material';
import { useAuth } from '../../lib/context/userContext';
import { useCustomTheme } from '../../lib/context/themeContext';
import { SchedulesProps } from '../../lib/interface';

interface SchedulesModalProps {
  open: boolean;
  onClose: () => void;
  schedule?: SchedulesProps | null;
  selectedDate: string;
  onSave: (schedule: SchedulesProps) => void;
  onDelete?: (scheduleId: string) => void;
  onDateChange?: (date: string) => void;
  existingSchedules?: SchedulesProps[];
}

const SchedulesModal: React.FC<SchedulesModalProps> = ({
  open,
  onClose,
  schedule,
  selectedDate,
  onSave,
  onDelete,
  onDateChange,
  existingSchedules = [],
}) => {
  const { user } = useAuth();
  const { theme } = useCustomTheme();
  const muiTheme = useTheme();
  const isMobile = useMediaQuery(muiTheme.breakpoints.down('sm'));

  const [userHasEditedTimes, setUserHasEditedTimes] = useState(false);

  // Helper to suggest next start time
  const suggestNextStartTime = useCallback((existing: SchedulesProps[]) => {
    const timedSchedules = existing.filter(s => !s.isFlexible && s.startTime);
    if (timedSchedules.length === 0) {
      const now = new Date();
      const nextHour = new Date(now.getTime() + 60 * 60 * 1000);
      nextHour.setMinutes(0);
      const start = `${String(nextHour.getHours()).padStart(2, '0')}:00`;
      const end = `${String((nextHour.getHours() + 1) % 24).padStart(2, '0')}:00`;
      return { startTime: start, endTime: end };
    }

    const sorted = [...timedSchedules].sort((a, b) => a.startTime.localeCompare(b.startTime));
    const last = sorted[sorted.length - 1];
    const start = last.endTime || last.startTime;
    
    const duration = last.duration || 30;
    const [h, m] = start.split(':').map(Number);
    const endDate = new Date();
    endDate.setHours(h, m + duration);
    const end = `${String(endDate.getHours()).padStart(2, '0')}:${String(endDate.getMinutes()).padStart(2, '0')}`;
    
    return { startTime: start, endTime: end };
  }, []);



  //   const hours = now.getHours().toString().padStart(2, '0');
  //   const minutes = now.getMinutes().toString().padStart(2, '0');
  //   return `${hours}:${minutes}`;
  // };

  const [formData, setFormData] = useState<Partial<SchedulesProps>>({
    title: '',
    startTime: '',
    endTime: '',
    objective: '',
    duration: 0,
    status: 'pending',
    priority: 'medium',
    reminder: {
      before: 10,
      method: 'notification',
    },
    repeat: 'none',
    autoGenerated: false,
    colorCode: '#E3F2FD',
    isFlexible: false,
  });

  const timeConflict = useMemo(() => {
    if (formData.isFlexible || !formData.startTime) return false;
    const start = formData.startTime;
    
    let end = formData.endTime;
    if (!end) {
      const [h, m] = start.split(':').map(Number);
      const date = new Date();
      date.setHours(h, m + 30);
      end = `${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`;
    }

    return existingSchedules.some((s) => {
      if (s.isFlexible || s.id === schedule?.id) return false;
      const sStart = s.startTime;
      const sEnd = s.endTime || s.startTime;
      return start < sEnd && sStart < end;
    });
  }, [formData.startTime, formData.endTime, formData.isFlexible, existingSchedules, schedule]);

  const [advancedOpen, setAdvancedOpen] = useState(false);
  const [customReminderDate, setCustomReminderDate] = useState<Date | null>(
    null,
  );
  const [reminderMethod, setReminderMethod] = useState<'whatsapp' | 'push'>(
    'whatsapp',
  );
  const [reminderActive, setReminderActive] = useState(false);
  const handleQuickReminderDate = (
    type: 'tomorrow' | 'afterTomorrow' | 'endOfWeek',
  ) => {
    const date = new Date();
    if (type === 'tomorrow') {
      date.setDate(date.getDate() + 1);
    } else if (type === 'afterTomorrow') {
      date.setDate(date.getDate() + 2);
    } else if (type === 'endOfWeek') {
      const day = date.getDay();
      const diff = day === 0 ? 7 : 7 - day;
      date.setDate(date.getDate() + diff);
    }
    const current = customReminderDate ? new Date(customReminderDate) : new Date();
    current.setFullYear(date.getFullYear());
    current.setMonth(date.getMonth());
    current.setDate(date.getDate());
    setCustomReminderDate(current);
  };

  const titleInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (open) {
      // Small delay to ensure Dialog transition is underway and focus trap is ready
      const timer = setTimeout(() => {
        if (titleInputRef.current) {
          titleInputRef.current.focus();
        }
      }, 100);
      return () => clearTimeout(timer);
    }
  }, [open]);

  const handleQuickDate = (
    type: 'tomorrow' | 'afterTomorrow' | 'endOfWeek',
  ) => {
    const date = new Date();
    if (type === 'tomorrow') {
      date.setDate(date.getDate() + 1);
    } else if (type === 'afterTomorrow') {
      date.setDate(date.getDate() + 2);
    } else if (type === 'endOfWeek') {
      const day = date.getDay();
      const diff = day === 0 ? 7 : 7 - day;
      date.setDate(date.getDate() + diff);
    }

    const yyyy = date.getFullYear();
    const mm = String(date.getMonth() + 1).padStart(2, '0');
    const dd = String(date.getDate()).padStart(2, '0');
    const formattedDate = `${yyyy}-${mm}-${dd}`;

    if (onDateChange) {
      onDateChange(formattedDate);
    }
  };

  const priorityOptions = [
    { value: 'low', label: 'Low', color: '#4caf50' },
    { value: 'medium', label: 'Medium', color: '#2196f3' },
    { value: 'high', label: 'High', color: '#ff9800' },
    { value: 'critical', label: 'Critical', color: '#f44336' },
  ];

  const reminderMethods = [
    { value: 'notification', label: 'Notification' },
    { value: 'whatsapp', label: 'WhatsApp' },
    { value: 'email', label: 'Email' },
  ];

  const repeatOptions = [
    { value: 'none', label: 'No Repeat' },
    { value: 'daily', label: 'Daily' },
    { value: 'weekly', label: 'Weekly' },
    { value: 'monthly', label: 'Monthly' },
  ];

  const dynamicQuickTimes = useMemo(() => {
    const now = new Date();
    const today = now.toISOString().split('T')[0];

    // For future dates, show standard slots
    if (selectedDate !== today) return ['09:00', '13:00', '17:00', '21:00'];

    const currentHour = now.getHours();
    let offsets: number[] = [];

    if (currentHour <= 14) {
      // First two: 1h distance | Next two: 2h distance
      // e.g. at 14:00 (2 PM) -> 15:00, 16:00, 18:00, 20:00
      offsets = [1, 2, 4, 6];
    } else {
      // Distance each 1 hour
      // e.g. at 15:00 (3 PM) -> 16:00, 17:00, 18:00, 19:00
      offsets = [1, 2, 3, 4];
    }

    return offsets
      .map((offset) => currentHour + offset)
      .filter((h) => h < 24)
      .map((h) => `${String(h).padStart(2, '0')}:00`);
  }, [selectedDate]);

  const applyDuration = (minutes: number) => {
    if (!formData.startTime) return;
    const [h, m] = formData.startTime.split(':').map(Number);
    const date = new Date();
    date.setHours(h, m + minutes);
    const endH = String(date.getHours()).padStart(2, '0');
    const endM = String(date.getMinutes()).padStart(2, '0');
    const newEndTime = `${endH}:${endM}`;
    handleInputChange('endTime', newEndTime);
    handleDurationChange(formData.startTime, newEndTime);
  };

  // Initialize form data when modal opens
  useEffect(() => {
    if (open) {
      setUserHasEditedTimes(false);
      if (schedule) {
        setFormData({
          title: schedule.title,
          startTime: schedule.startTime,
          endTime: schedule.endTime,
          objective: schedule.objective,
          duration: schedule.duration,
          status: schedule.status || 'pending',
          priority: schedule.priority,
          reminder: schedule.reminder,
          repeat: schedule.repeat,
          autoGenerated: schedule.autoGenerated,
          colorCode: schedule.colorCode,
          isFlexible: schedule.isFlexible || false,
        });
        if (schedule.hasReminder && schedule.reminderDate) {
          const reminderDate = schedule.reminderDate;
          if (
            typeof reminderDate === 'object' &&
            reminderDate !== null &&
            'toDate' in reminderDate &&
            typeof (reminderDate as { toDate?: unknown }).toDate === 'function'
          ) {
            setCustomReminderDate(
              (reminderDate as { toDate: () => Date }).toDate(),
            );
          } else {
            setCustomReminderDate(
              new Date(reminderDate as string | number | Date),
            );
          }
        } else {
          setCustomReminderDate(null);
        }
        // Restore reminder method from saved schedule
        if (schedule.reminder?.method === 'push') {
          setReminderMethod('push');
        } else if (schedule.reminder?.method === 'whatsapp') {
          setReminderMethod('whatsapp');
        } else {
          setReminderMethod('whatsapp');
        }
      } else {
        const suggestion = suggestNextStartTime(existingSchedules);
        setFormData({
          title: '',
          startTime: suggestion.startTime,
          endTime: suggestion.endTime,
          objective: '',
          duration: 30,
          status: 'pending',
          priority: 'medium',
          reminder: {
            before: 10,
            method: 'notification',
          },
          repeat: 'none',
          autoGenerated: false,
          colorCode: '#E3F2FD',
          isFlexible: false,
        });
        setCustomReminderDate(null);
        setReminderMethod('whatsapp');
      }
    }
  }, [open, schedule, existingSchedules, suggestNextStartTime]);

  // Re-suggest start/end times if date (existingSchedules) changes and user hasn't edited times
  useEffect(() => {
    if (open && !schedule && !userHasEditedTimes) {
      const suggestion = suggestNextStartTime(existingSchedules);
      setFormData((prev) => ({
        ...prev,
        startTime: suggestion.startTime,
        endTime: suggestion.endTime,
      }));
    }
  }, [existingSchedules, open, schedule, userHasEditedTimes, suggestNextStartTime]);

  const handleInputChange = (
    field: keyof SchedulesProps,
    value:
      | string
      | number
      | boolean
      | { before: number; method: string }
      | string[],
  ) => {
    setFormData((prev) => ({
      ...prev,
      [field]: value,
    }));
  };

  const handleDurationChange = (startTime: string, endTime: string) => {
    if (startTime && endTime) {
      const [startHour, startMin] = startTime.split(':').map(Number);
      const [endHour, endMin] = endTime.split(':').map(Number);

      const startMinutes = startHour * 60 + startMin;
      const endMinutes = endHour * 60 + endMin;

      const duration = endMinutes - startMinutes;
      if (duration > 0) {
        setFormData((prev) => ({
          ...prev,
          duration,
        }));
      }
    }
  };

  const handleSave = () => {
    const isFlexible = formData.isFlexible || false;
    if (!user || !formData.title || (!isFlexible && !formData.startTime)) {
      console.error('Missing required fields:', {
        user: !!user,
        title: formData.title,
        startTime: formData.startTime,
        isFlexible,
      });
      return;
    }

    // If no end time provided, assume 30 minutes duration
    const startTime = formData.startTime || '00:00';
    let endTime = formData.endTime;
    if (!endTime && startTime) {
      const [hours, minutes] = formData.startTime.split(':').map(Number);
      const startMinutes = hours * 60 + minutes;
      const endMinutes = startMinutes + 30; // Default 30 minutes
      const endHours = Math.floor(endMinutes / 60);
      const endMins = endMinutes % 60;
      endTime = `${endHours.toString().padStart(2, '0')}:${endMins
        .toString()
        .padStart(2, '0')}`;
    }

    // Determine if we need an RTDB reminder entry
    const isRtdbReminder =
      reminderMethod === 'whatsapp' || reminderMethod === 'push';
    let hasReminder = false;
    let reminderDateVal: Date | null = null;

    if (isRtdbReminder) {
      hasReminder = true;
      if (customReminderDate) {
        reminderDateVal = customReminderDate;
      } else if (selectedDate && startTime) {
        const scheduleStart = new Date(`${selectedDate}T${startTime}`);
        const beforeMinutes = formData.reminder?.before ?? 10;
        reminderDateVal = new Date(
          scheduleStart.getTime() - beforeMinutes * 60 * 1000,
        );
      }

      // Safety check to avoid adding past dates to RTDB
      if (reminderDateVal && reminderDateVal.getTime() <= Date.now()) {
        reminderDateVal = new Date(Date.now() + 5 * 60000); // 5 mins buffer
      }
    }

    const scheduleData: SchedulesProps = {
      ...(schedule?.id ? { id: schedule.id } : {}),
      userId: user.uid,
      date: isFlexible ? '' : selectedDate,
      title: formData.title,
      startTime: startTime,
      endTime: endTime || startTime,
      objective: formData.objective || '',
      duration: formData.duration || 30,
      status: formData.status || 'pending',
      priority: formData.priority || 'medium',
      reminder: {
        before: formData.reminder?.before ?? 10,
        method: reminderMethod as SchedulesProps['reminder']['method'],
      },
      hasReminder,
      reminderDate: reminderDateVal,
      repeat: formData.repeat || 'none',
      autoGenerated: formData.autoGenerated || false,
      colorCode: formData.colorCode || '#E3F2FD',
      isFlexible: formData.isFlexible || false,
      createdAt: schedule?.createdAt || new Date(),
      updatedAt: new Date(),
    };

    console.log('Saving schedule data:', scheduleData);
    onSave(scheduleData);
    onClose();
  };

  const handleDelete = () => {
    if (schedule?.id && onDelete) {
      onDelete(schedule.id);
      onClose();
    }
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="sm"
      fullWidth
      fullScreen={isMobile}
      PaperProps={{
        className: `rounded-[28px] overflow-hidden shadow-2xl border transition-all ${
          theme?.mode === 'dark'
            ? 'bg-slate-900 border-slate-800 text-slate-100'
            : 'bg-white border-slate-100 text-slate-850'
        }`,
        sx: { 
          borderRadius: '28px',
          backgroundColor: theme?.mode === 'dark' ? '#0f172a' : '#ffffff',
          color: theme?.mode === 'dark' ? '#f1f5f9' : '#0f172a',
        },
      }}
    >
      {/* Premium Gradient Header */}
      <Box className="p-6 bg-gradient-to-br from-violet-500 to-indigo-700 text-white flex justify-between items-center">
        <Box>
          <Typography variant="h6" className="font-extrabold">
            {schedule ? 'Edit Schedule' : 'Plan Your Day'}
          </Typography>
          <Typography variant="body2" className="opacity-90">
            {schedule
              ? 'Refine your session details'
              : 'Create a new productive session'}
          </Typography>
        </Box>
        <IconButton
          onClick={onClose}
          className="text-white hover:bg-white/20 transition-colors"
        >
          <CloseIcon />
        </IconButton>
      </Box>

      <DialogContent className="p-6">
        <Box className="flex flex-col gap-10 pt-4">
          {/* Title Input */}
          <Box>
            <Typography className="text-[11px] font-extrabold text-slate-400 dark:text-slate-500 uppercase tracking-[0.2em] mb-3 ml-1">
              🏷️ Title
            </Typography>
            <TextField
              inputRef={titleInputRef}
              fullWidth
              value={formData.title}
              onChange={(e) => handleInputChange('title', e.target.value)}
              required
              variant="outlined"
              placeholder="What's the focus?"
              sx={{
                '& .MuiOutlinedInput-root': {
                  borderRadius: '16px',
                  backgroundColor:
                    theme?.mode === 'dark' ? 'rgba(15, 23, 42, 0.5)' : '#fff',
                  fontSize: '1.15rem',
                  fontWeight: 700,
                  transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
                  '& fieldset': {
                    borderColor: theme?.mode === 'dark' ? '#334155' : '#e2e8f0',
                  },
                  '&:hover fieldset': { borderColor: '#8b5cf6' },
                  '&.Mui-focused fieldset': {
                    borderColor: '#8b5cf6',
                    borderWidth: '2px',
                  },
                  '&.Mui-focused': {
                    boxShadow: '0 0 0 4px rgba(139, 92, 246, 0.1)',
                  },
                },
              }}
            />
          </Box>

          {/* Status Checkbox (Edit Mode Only) */}
          {schedule && (
            <Box sx={{ mt: -2, mb: -1, ml: 1 }}>
              <FormControlLabel
                control={
                  <Checkbox
                    checked={formData.status === 'completed'}
                    onChange={(e) => handleInputChange('status', e.target.checked ? 'completed' : 'pending')}
                    sx={{
                      color: '#8b5cf6',
                      '&.Mui-checked': { color: '#8b5cf6' },
                    }}
                  />
                }
                label={
                  <Typography className="text-sm font-bold text-slate-800 dark:text-slate-200">
                    I have done it
                  </Typography>
                }
              />
            </Box>
          )}

          {/* Date / Deadline Section */}
          <Box className={`p-6 rounded-[24px] border transition-all ${
            theme?.mode === 'dark'
              ? 'bg-slate-900/30 border-slate-800'
              : 'bg-slate-50 border-slate-100'
          }`}>
            <Box className="flex items-center justify-between mb-4">
              <Typography className="text-[11px] font-extrabold text-violet-600 dark:text-violet-400 uppercase tracking-[0.2em]">
                📅 Schedule Date
              </Typography>
              <Button
                onClick={() =>
                  handleInputChange('isFlexible', !formData.isFlexible)
                }
                variant={formData.isFlexible ? 'contained' : 'outlined'}
                size="small"
                className={`rounded-full px-4 font-bold transition-all text-[10px] ${formData.isFlexible ? 'bg-violet-600 shadow-lg shadow-violet-500/30' : ''}`}
              >
                {formData.isFlexible ? '✨ Daily Active' : 'Show me Daily'}
              </Button>
            </Box>

            <Collapse in={!formData.isFlexible}>
              <Box>
                <TextField
                  type="date"
                  value={selectedDate}
                  onChange={(e) => onDateChange && onDateChange(e.target.value)}
                  fullWidth
                  sx={{
                    '& .MuiOutlinedInput-root': {
                      borderRadius: '16px',
                      backgroundColor:
                        theme?.mode === 'dark' ? '#1e3a8a20' : '#f0f7ff',
                      '& fieldset': {
                        borderColor: '#3b82f6',
                        borderWidth: '2px',
                      },
                    },
                    '& .MuiInputBase-input': {
                      textAlign: 'center',
                      fontWeight: 800,
                      color: '#2563eb',
                      fontSize: '1.1rem',
                      letterSpacing: '1px',
                    },
                  }}
                  helperText={
                    <Typography
                      variant="caption"
                      className="text-slate-400 dark:text-slate-500 font-bold ml-1 uppercase tracking-wider"
                    >
                      {new Date(selectedDate).toLocaleDateString('en-US', {
                        weekday: 'long',
                        month: 'long',
                        day: 'numeric',
                      })}
                    </Typography>
                  }
                />
                <Stack
                  direction="row"
                  spacing={1}
                  mt={2.5}
                  className="overflow-x-auto pb-1 no-scrollbar flex-nowrap"
                >
                  {[
                    { label: 'Tomorrow', value: 'tomorrow' },
                    { label: 'In 2 Days', value: 'afterTomorrow' },
                    { label: 'Weekend', value: 'endOfWeek' },
                  ].map((item) => (
                    <Button
                      key={item.value}
                      variant="outlined"
                      onClick={() =>
                        handleQuickDate(
                          item.value as
                          | 'tomorrow'
                          | 'afterTomorrow'
                          | 'endOfWeek',
                        )
                      }
                      className="rounded-full normal-case text-[12px] font-bold px-5 py-1.5 whitespace-nowrap border-slate-200 dark:border-slate-700 text-slate-500 dark:text-slate-400 hover:border-violet-400 hover:text-violet-500 hover:bg-violet-50 dark:hover:bg-violet-900/10 transition-all"
                    >
                      {item.label}
                    </Button>
                  ))}
                </Stack>
              </Box>
            </Collapse>
          </Box>

          {/* Time Selection */}
          <Box className="relative">
            <Typography className="text-[11px] font-extrabold text-slate-400 dark:text-slate-500 uppercase tracking-[0.2em] mb-3 ml-1">
              ⏰ Session Timing
            </Typography>

            <Box className={`p-4 rounded-[20px] border shadow-sm ${
              theme?.mode === 'dark'
                ? 'bg-slate-950/40 border-slate-800'
                : 'bg-white border-slate-100'
            }`}>
              <Stack
                direction={{ xs: 'column', sm: 'row' }}
                alignItems="center"
                spacing={2}
              >
                {/* Start Time Pill */}
                <Box className="flex-1 w-full">
                  <TextField
                    type="time"
                    value={formData.startTime}
                    onChange={(e) => {
                      handleInputChange('startTime', e.target.value);
                      setUserHasEditedTimes(true);
                      if (formData.endTime)
                        handleDurationChange(e.target.value, formData.endTime);
                    }}
                    fullWidth
                    InputLabelProps={{ shrink: true }}
                    InputProps={{
                      className: theme?.mode === 'dark'
                        ? 'bg-slate-800 text-slate-100 [color-scheme:dark]'
                        : 'bg-slate-50 text-slate-900 [color-scheme:light]',
                    }}
                    sx={{
                      '& .MuiOutlinedInput-root': {
                        borderRadius: '12px',
                        border: 'none',
                        '& fieldset': { border: 'none' },
                        height: '48px',
                        backgroundColor: theme?.mode === 'dark' ? '#1e293b' : '#f8fafc',
                      },
                      '& .MuiInputBase-input': {
                        fontWeight: 800,
                        textAlign: 'center',
                        fontSize: '1rem',
                        color: theme?.mode === 'dark' ? '#f1f5f9' : '#0f172a',
                      },
                    }}
                  />
                  <Box className="flex flex-wrap justify-center gap-1.5 mt-2">
                    {dynamicQuickTimes.slice(0, 3).map((time) => (
                      <Button
                        key={time}
                        onClick={() => {
                          handleInputChange('startTime', time);
                          setUserHasEditedTimes(true);
                        }}
                        className="min-w-0 px-2 py-0.5 text-[10px] font-bold rounded-full bg-slate-50 dark:bg-slate-800 text-slate-500 dark:text-slate-400 border border-slate-100 dark:border-slate-700 hover:bg-violet-500 hover:text-white transition-all"
                      >
                        {time}
                      </Button>
                    ))}
                  </Box>
                </Box>

                {/* Connection Arrow */}
                <Box className="hidden sm:block text-slate-300">
                  <Typography variant="h5">→</Typography>
                </Box>

                {/* End Time Pill */}
                <Box className="flex-1 w-full">
                  <TextField
                    type="time"
                    value={formData.endTime}
                    onChange={(e) => {
                      handleInputChange('endTime', e.target.value);
                      setUserHasEditedTimes(true);
                      if (formData.startTime)
                        handleDurationChange(
                          formData.startTime,
                          e.target.value,
                        );
                    }}
                    fullWidth
                    InputLabelProps={{ shrink: true }}
                    InputProps={{
                      className: theme?.mode === 'dark'
                        ? 'bg-slate-800 text-slate-100 [color-scheme:dark]'
                        : 'bg-slate-50 text-slate-900 [color-scheme:light]',
                    }}
                    sx={{
                      '& .MuiOutlinedInput-root': {
                        borderRadius: '12px',
                        border: 'none',
                        '& fieldset': { border: 'none' },
                        height: '48px',
                        backgroundColor: theme?.mode === 'dark' ? '#1e293b' : '#f8fafc',
                      },
                      '& .MuiInputBase-input': {
                        fontWeight: 800,
                        textAlign: 'center',
                        fontSize: '1rem',
                        color: theme?.mode === 'dark' ? '#f1f5f9' : '#0f172a',
                      },
                    }}
                  />
                  <Box className="flex flex-wrap justify-center gap-1.5 mt-2">
                    {[15, 30, 60].map((mins) => (
                      <Button
                        key={mins}
                        disabled={!formData.startTime}
                        onClick={() => {
                          applyDuration(mins);
                          setUserHasEditedTimes(true);
                        }}
                        className="min-w-0 px-2 py-0.5 text-[10px] font-bold rounded-full bg-slate-50 dark:bg-slate-800 text-slate-500 dark:text-slate-400 border border-slate-100 dark:border-slate-700 hover:bg-indigo-500 hover:text-white transition-all"
                      >
                        +{mins}m
                      </Button>
                    ))}
                  </Box>
                </Box>
              </Stack>

              {formData.duration ? (
                <Box className="mt-3 pt-3 border-t border-slate-50 dark:border-slate-800 text-center">
                  <Typography className="text-[10px] font-bold text-violet-500 dark:text-violet-400 uppercase tracking-widest">
                    ⏱️ Total: {formData.duration} Minutes
                  </Typography>
                </Box>
              ) : null}

              {timeConflict && (
                <Box className="mt-3 pt-3 border-t border-slate-50 dark:border-slate-800 text-center">
                  <Typography color="error" variant="caption" sx={{ fontWeight: 'bold' }}>
                    ⚠️ Conflict: This overlaps with another schedule on this day.
                  </Typography>
                </Box>
              )}
            </Box>
          </Box>

          {/* Objective */}
          <Box>
            <Typography className="text-[11px] font-extrabold text-slate-400 dark:text-slate-500 uppercase tracking-[0.2em] mb-3 ml-1">
              🎯 Objective
            </Typography>
            <TextField
              fullWidth
              value={formData.objective}
              onChange={(e) => handleInputChange('objective', e.target.value)}
              placeholder="What's the desired outcome?"
              variant="outlined"
              sx={{
                '& .MuiOutlinedInput-root': {
                  borderRadius: '16px',
                  backgroundColor:
                    theme?.mode === 'dark' ? 'rgba(15, 23, 42, 0.5)' : '#fff',
                  '&:hover fieldset': { borderColor: '#8b5cf6' },
                  '&.Mui-focused fieldset': { borderColor: '#8b5cf6' },
                },
              }}
              helperText={
                <span className="text-[11px] font-medium text-slate-400">
                  💡 A clear goal significantly improves focus
                </span>
              }
            />
          </Box>

          {/* Reminder Section — WhatsApp or Push Notification */}
          <Box
            className={`
              p-4 rounded-[24px] border transition-all
              ${theme?.mode === 'dark' ? 'bg-slate-900/40 border-slate-700' : 'bg-slate-50 border-slate-200'}
            `}
          >
            <Box className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
              <Box className="min-w-0">
                <Typography className="text-[11px] font-extrabold text-violet-600 dark:text-violet-400 uppercase tracking-[0.2em]">
                  🔔 Reminder
                </Typography>
                <Typography className="mt-1 text-[12px] text-slate-600 dark:text-slate-300 truncate">
                  Set a quick session alert.
                </Typography>
              </Box>
              <FormControlLabel
                control={
                  <Switch
                    checked={reminderActive}
                    onChange={(e) => {
                      const isChecked = e.target.checked;
                      setReminderActive(isChecked);
                      if (isChecked && !customReminderDate) {
                        const d = new Date();
                        d.setHours(d.getHours() + 1, 0, 0, 0);
                        setCustomReminderDate(d);
                      }
                      if (!isChecked) {
                        setCustomReminderDate(null);
                      }
                      handleInputChange('reminder', {
                        before: formData.reminder?.before ?? 10,
                        method: isChecked ? reminderMethod : 'notification',
                      });
                    }}
                    sx={{
                      '& .MuiSwitch-switchBase.Mui-checked': {
                        color: '#8b5cf6',
                      },
                      '& .MuiSwitch-switchBase.Mui-checked + .MuiSwitch-track':
                      {
                        backgroundColor: '#8b5cf6',
                      },
                    }}
                  />
                }
                label=""
                sx={{ mr: 0 }}
              />
            </Box>

            <Collapse in={reminderActive} timeout="auto">
              <Box className="mt-4 space-y-4">
                <Box className="grid grid-cols-2 gap-2">
                  {[
                    { value: 'whatsapp', label: 'WhatsApp', icon: <WhatsAppIcon sx={{ fontSize: 15 }} /> },
                    { value: 'push', label: 'Push', icon: <PushIcon sx={{ fontSize: 15 }} /> },
                  ].map((option) => (
                    <button
                      key={option.value}
                      type="button"
                      onClick={() => {
                        setReminderMethod(option.value as 'whatsapp' | 'push');
                        handleInputChange('reminder', {
                          before: formData.reminder?.before ?? 10,
                          method: option.value === 'whatsapp' ? 'whatsapp' : 'push',
                        });
                      }}
                      className={`flex items-center justify-center gap-2 rounded-2xl border px-3 py-2 text-xs font-semibold transition-all ${reminderMethod === option.value
                        ? 'border-violet-500 bg-violet-50 text-violet-700 dark:bg-violet-500/10 dark:text-violet-200'
                        : 'border-slate-200 bg-white text-slate-500 hover:border-violet-300 hover:text-violet-700 dark:bg-slate-800 dark:text-slate-300 dark:hover:border-violet-500 dark:hover:text-violet-100'
                        }`}
                    >
                      {option.icon}
                      {option.label}
                    </button>
                  ))}
                </Box>

                {/* Custom Synced Date-Time Control Center */}
                <Box className="space-y-5 mt-4">
                  {/* Date Picker Section */}
                  <Box>
                    <Box className="flex items-center justify-between mb-2.5 px-1">
                      <Typography className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest flex items-center gap-1.5">
                        <CustomDateIcon style={{ fontSize: 13 }} />
                        Select Reminder Date
                      </Typography>
                    </Box>
                    <TextField
                      type="date"
                      value={customReminderDate ? `${customReminderDate.getFullYear()}-${String(customReminderDate.getMonth() + 1).padStart(2, '0')}-${String(customReminderDate.getDate()).padStart(2, '0')}` : ''}
                      onChange={(e) => {
                        if (e.target.value) {
                          const [y, m, d] = e.target.value.split('-').map(Number);
                          const current = customReminderDate ? new Date(customReminderDate) : new Date();
                          current.setFullYear(y);
                          current.setMonth(m - 1);
                          current.setDate(d);
                          setCustomReminderDate(current);
                        } else {
                          setCustomReminderDate(null);
                        }
                      }}
                      fullWidth
                      sx={{
                        '& .MuiOutlinedInput-root': {
                          borderRadius: '16px',
                          backgroundColor:
                            theme?.mode === 'dark' ? '#1e3a8a20' : '#f0f7ff',
                          '& fieldset': {
                            borderColor: '#3b82f6',
                            borderWidth: '2px',
                          },
                        },
                        '& .MuiInputBase-input': {
                          textAlign: 'center',
                          fontWeight: 800,
                          color: '#2563eb',
                          fontSize: '1.1rem',
                          letterSpacing: '1px',
                        },
                      }}
                      helperText={
                        customReminderDate && (
                          <Typography
                            variant="caption"
                            className="text-slate-400 dark:text-slate-500 font-bold ml-1 uppercase tracking-wider"
                          >
                            {customReminderDate.toLocaleDateString('en-US', {
                              weekday: 'long',
                              month: 'long',
                              day: 'numeric',
                            })}
                          </Typography>
                        )
                      }
                    />
                    <Stack
                      direction="row"
                      spacing={1}
                      mt={2}
                      className="overflow-x-auto pb-1 no-scrollbar flex-nowrap"
                    >
                      {[
                        { label: 'Tomorrow', value: 'tomorrow' },
                        { label: 'In 2 Days', value: 'afterTomorrow' },
                        { label: 'Weekend', value: 'endOfWeek' },
                      ].map((item) => (
                        <Button
                          key={item.value}
                          variant="outlined"
                          onClick={() => handleQuickReminderDate(item.value as 'tomorrow' | 'afterTomorrow' | 'endOfWeek')}
                          className="rounded-full normal-case text-[12px] font-bold px-5 py-1.5 whitespace-nowrap border-slate-200 dark:border-slate-700 text-slate-500 dark:text-slate-400 hover:border-violet-400 hover:text-violet-500 hover:bg-violet-50 dark:hover:bg-violet-900/10 transition-all"
                        >
                          {item.label}
                        </Button>
                      ))}
                    </Stack>
                  </Box>

                  {/* Expandable Reusable Custom Wheel Picker */}
                  {customReminderDate && (
                    <Box className="mt-3">
                      <CustomWheelTimePicker
                        value={customReminderDate}
                        isDark={theme?.mode === 'dark'}
                        onChange={(nextDate) => {
                          setCustomReminderDate(nextDate);
                        }}
                      />
                    </Box>
                  )}
                </Box>

                {reminderMethod === 'whatsapp' ? (
                  <FormControlLabel
                    control={
                      <Checkbox
                        checked={formData.reminder?.before === 10}
                        onChange={(e) =>
                          handleInputChange('reminder', {
                            ...formData.reminder,
                            before: e.target.checked ? 10 : 0,
                          })
                        }
                        sx={{
                          color: '#8b5cf6',
                          '&.Mui-checked': {
                            color: '#8b5cf6',
                          },
                        }}
                      />
                    }
                    label={
                      <Typography className="text-sm font-semibold text-slate-700 dark:text-slate-300">
                        Reminded me 10 mins before
                      </Typography>
                    }
                  />
                ) : (
                  <Box className="rounded-2xl border border-violet-200 bg-violet-50/70 p-3 text-sm text-violet-700 dark:border-violet-700/30 dark:bg-violet-950/20 dark:text-violet-200">
                    <Typography className="font-semibold">Push reminder</Typography>
                    <Typography className="mt-1 text-xs text-slate-600 dark:text-slate-400">
                      Sends a browser notification at the selected date/time. Enable push in{' '}
                      <a
                        href="/settings/push-notifications"
                        target="_blank"
                        className="underline font-semibold"
                      >
                        Settings
                      </a>
                      .
                    </Typography>
                  </Box>
                )}

                {reminderMethod === 'whatsapp' && (
                  <Typography className="text-[10px] text-slate-500 dark:text-slate-400">
                    Leave date/time empty to auto-send <strong>{formData.reminder?.before} minutes</strong> before start.
                  </Typography>
                )}
              </Box>
            </Collapse>
          </Box>

          {/* Advanced Section */}
          <Box className="mb-4">
            <Button
              onClick={() => setAdvancedOpen(!advancedOpen)}
              fullWidth
              startIcon={advancedOpen ? <ExpandLessIcon /> : <ExpandMoreIcon />}
              className="justify-start normal-case font-bold text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800/50 rounded-xl py-2"
            >
              {advancedOpen ? 'Hide' : 'More Options'} (Priority, Reminders)
            </Button>

            <Collapse in={advancedOpen} timeout="auto" unmountOnExit>
              <Box className="pt-4 space-y-4">
                <FormControl fullWidth>
                  <InputLabel className="font-bold">Priority Level</InputLabel>
                  <Select
                    value={formData.priority}
                    onChange={(e) =>
                      handleInputChange('priority', e.target.value)
                    }
                    label="Priority Level"
                    sx={{ borderRadius: '16px' }}
                  >
                    {priorityOptions.map((option) => (
                      <MenuItem key={option.value} value={option.value}>
                        <Box className="flex items-center gap-3">
                          <Box
                            className="w-3 h-3 rounded-full"
                            sx={{ backgroundColor: option.color }}
                          />
                          <Typography className="font-semibold text-sm">
                            {option.label}
                          </Typography>
                        </Box>
                      </MenuItem>
                    ))}
                  </Select>
                </FormControl>

                <Box className="grid grid-cols-2 gap-4">
                  <TextField
                    label="Reminder (mins before)"
                    type="number"
                    value={formData.reminder?.before}
                    onChange={(e) =>
                      handleInputChange('reminder', {
                        ...formData.reminder,
                        before: parseInt(e.target.value) || 0,
                      })
                    }
                    sx={{
                      '& .MuiOutlinedInput-root': { borderRadius: '16px' },
                    }}
                  />
                  <FormControl>
                    <InputLabel>Alert Method</InputLabel>
                    <Select
                      value={formData.reminder?.method}
                      onChange={(e) =>
                        handleInputChange('reminder', {
                          ...formData.reminder,
                          method: e.target.value,
                        })
                      }
                      label="Alert Method"
                      sx={{ borderRadius: '16px' }}
                    >
                      {reminderMethods.map((m) => (
                        <MenuItem key={m.value} value={m.value} disabled={m.value === 'email'}>
                          {m.label}
                        </MenuItem>
                      ))}
                    </Select>
                  </FormControl>
                </Box>

                <FormControl fullWidth>
                  <InputLabel>Repeat Interval</InputLabel>
                  <Select
                    value={formData.repeat}
                    onChange={(e) =>
                      handleInputChange('repeat', e.target.value)
                    }
                    label="Repeat Interval"
                    sx={{ borderRadius: '16px' }}
                  >
                    {repeatOptions.map((o) => (
                      <MenuItem key={o.value} value={o.value}>
                        {o.label}
                      </MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Box>
            </Collapse>
          </Box>
        </Box>
      </DialogContent>

      <DialogActions className={`p-6 border-t gap-2 ${
        theme?.mode === 'dark'
          ? 'bg-slate-950/20 border-slate-800'
          : 'bg-slate-50/50 border-slate-100'
      }`}>
        {schedule && onDelete && (
          <Button
            onClick={handleDelete}
            color="error"
            variant="outlined"
            className="rounded-xl border-2 font-bold px-6 py-2 normal-case mr-auto"
            startIcon={<DeleteIcon />}
          >
            <span className="hidden sm:inline">Delete</span>
          </Button>
        )}
        <Button
          onClick={onClose}
          variant="outlined"
          color="error"
          className="rounded-xl font-bold px-6 py-2 normal-case border border-red-500 text-red-500 hover:bg-red-50 dark:border-red-500/40 dark:text-red-400 dark:hover:bg-red-950/30 transition-all"
        >
          Cancel
        </Button>
        <Button
          onClick={handleSave}
          variant="contained"
          disabled={
            !formData.title || (!formData.isFlexible && !formData.startTime) || timeConflict
          }
          className="rounded-xl font-extrabold px-8 py-2 normal-case bg-gradient-to-r from-violet-600 to-indigo-600 shadow-lg shadow-indigo-500/30 hover:shadow-indigo-500/50"
        >
          {schedule ? 'Update Session' : 'Start Planning'}
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default SchedulesModal;
