'use client';

import React, { useState, useEffect, useRef, useMemo } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  TextField,
  Box,
  Typography,
  Stack,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  IconButton,
  Collapse,
  useTheme,
  useMediaQuery,
} from '@mui/material';
import {
  Close as CloseIcon,
  Delete as DeleteIcon,
  ExpandMore as ExpandMoreIcon,
  ExpandLess as ExpandLessIcon,
} from '@mui/icons-material';
import { motion } from 'framer-motion';
import { useAuth } from '../../lib/context/userContext';
import { useCustomTheme } from '../../lib/context/themeContext';
import { SchedulesProps } from '../../lib/interface';

interface SchedulesModalProps {
  open: boolean;
  onClose: () => void;
  schedule?: SchedulesProps | null;
  selectedDate: string;
  onSave: (schedule: SchedulesProps) => void;
  onDelete?: (scheduleId: string) => void;
  onDateChange?: (date: string) => void;
}

const SchedulesModal: React.FC<SchedulesModalProps> = ({
  open,
  onClose,
  schedule,
  selectedDate,
  onSave,
  onDelete,
  onDateChange,
}) => {
  const { user } = useAuth();
  const { theme } = useCustomTheme();
  const muiTheme = useTheme();
  const isMobile = useMediaQuery(muiTheme.breakpoints.down('sm'));

  // Get current time for default values
  // const getCurrentTime = () => {
  //   const now = new Date();
  //   const hours = now.getHours().toString().padStart(2, '0');
  //   const minutes = now.getMinutes().toString().padStart(2, '0');
  //   return `${hours}:${minutes}`;
  // };

  const [formData, setFormData] = useState<Partial<SchedulesProps>>({
    title: '',
    startTime: '',
    endTime: '',
    objective: '',
    duration: 0,
    status: 'pending',
    priority: 'medium',
    reminder: {
      before: 10,
      method: 'notification',
    },
    repeat: 'none',
    autoGenerated: false,
    colorCode: '#E3F2FD',
  });

  const [advancedOpen, setAdvancedOpen] = useState(false);
  const titleInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (open) {
      const timer = setTimeout(() => {
        titleInputRef.current?.focus();
      }, 100);
      return () => clearTimeout(timer);
    }
  }, [open]);

  const handleQuickDate = (type: 'tomorrow' | 'afterTomorrow' | 'endOfWeek') => {
    const date = new Date();
    if (type === 'tomorrow') {
      date.setDate(date.getDate() + 1);
    } else if (type === 'afterTomorrow') {
      date.setDate(date.getDate() + 2);
    } else if (type === 'endOfWeek') {
      const day = date.getDay();
      const diff = day === 0 ? 7 : 7 - day;
      date.setDate(date.getDate() + diff);
    }

    const yyyy = date.getFullYear();
    const mm = String(date.getMonth() + 1).padStart(2, '0');
    const dd = String(date.getDate()).padStart(2, '0');
    const formattedDate = `${yyyy}-${mm}-${dd}`;

    if (onDateChange) {
      onDateChange(formattedDate);
    }
  };


  const priorityOptions = [
    { value: 'low', label: 'Low', color: '#4caf50' },
    { value: 'medium', label: 'Medium', color: '#2196f3' },
    { value: 'high', label: 'High', color: '#ff9800' },
    { value: 'critical', label: 'Critical', color: '#f44336' },
  ];

  const reminderMethods = [
    { value: 'notification', label: 'Notification' },
    { value: 'whatsapp', label: 'WhatsApp' },
    { value: 'email', label: 'Email' },
  ];

  const repeatOptions = [
    { value: 'none', label: 'No Repeat' },
    { value: 'daily', label: 'Daily' },
    { value: 'weekly', label: 'Weekly' },
    { value: 'monthly', label: 'Monthly' },
  ];

  const dynamicQuickTimes = useMemo(() => {
    const now = new Date();
    const today = now.toISOString().split('T')[0];
    
    // For future dates, show standard slots
    if (selectedDate !== today) return ['09:00', '13:00', '17:00', '21:00'];

    const currentHour = now.getHours();
    let offsets: number[] = [];
    
    if (currentHour <= 14) {
      // First two: 1h distance | Next two: 2h distance
      // e.g. at 14:00 (2 PM) -> 15:00, 16:00, 18:00, 20:00
      offsets = [1, 2, 4, 6];
    } else {
      // Distance each 1 hour
      // e.g. at 15:00 (3 PM) -> 16:00, 17:00, 18:00, 19:00
      offsets = [1, 2, 3, 4];
    }

    return offsets
      .map(offset => currentHour + offset)
      .filter(h => h < 24)
      .map(h => `${String(h).padStart(2, '0')}:00`);
  }, [selectedDate]);

  const applyDuration = (minutes: number) => {
    if (!formData.startTime) return;
    const [h, m] = formData.startTime.split(':').map(Number);
    const date = new Date();
    date.setHours(h, m + minutes);
    const endH = String(date.getHours()).padStart(2, '0');
    const endM = String(date.getMinutes()).padStart(2, '0');
    const newEndTime = `${endH}:${endM}`;
    handleInputChange('endTime', newEndTime);
    handleDurationChange(formData.startTime, newEndTime);
  };

  const timeFieldStyle = {
    '& .MuiOutlinedInput-root': {
      borderRadius: 3,
      backgroundColor: theme?.mode === 'dark' ? 'rgba(15, 23, 42, 0.6)' : '#fff',
      transition: 'all 0.2s ease',
      '&:hover fieldset': { borderColor: muiTheme.palette.primary.main },
      '&.Mui-focused fieldset': { borderWidth: '2px' },
    }
  };

  const quickTimeBtnStyle = {
    minWidth: 0,
    px: 1.5,
    py: 0.5,
    fontSize: '0.75rem',
    borderRadius: '12px',
    color: theme?.mode === 'dark' ? '#94a3b8' : '#64748b',
    border: `1px solid ${muiTheme.palette.divider}`,
    textTransform: 'none',
    '&:hover': {
      bgcolor: 'primary.main',
      color: 'white',
      borderColor: 'primary.main',
      transform: 'translateY(-1px)',
    },
    transition: 'all 0.2s',
  };

  // Initialize form data when modal opens
  useEffect(() => {
    if (open) {
      if (schedule) {
        setFormData({
          title: schedule.title,
          startTime: schedule.startTime,
          endTime: schedule.endTime,
          objective: schedule.objective,
          duration: schedule.duration,
          priority: schedule.priority,
          reminder: schedule.reminder,
          repeat: schedule.repeat,
          autoGenerated: schedule.autoGenerated,
          colorCode: schedule.colorCode,
        });
      } else {
        setFormData({
          title: '',
          startTime: '',
          endTime: '',
          objective: '',
          duration: 0,
          status: 'pending',
          priority: 'medium',
          reminder: {
            before: 10,
            method: 'notification',
          },
          repeat: 'none',
          autoGenerated: false,
          colorCode: '#E3F2FD',
        });
      }
    }
  }, [open, schedule]);

  const handleInputChange = (
    field: keyof SchedulesProps,
    value:
      | string
      | number
      | boolean
      | { before: number; method: string }
      | string[],
  ) => {
    setFormData((prev) => ({
      ...prev,
      [field]: value,
    }));
  };

  const handleDurationChange = (startTime: string, endTime: string) => {
    if (startTime && endTime) {
      const [startHour, startMin] = startTime.split(':').map(Number);
      const [endHour, endMin] = endTime.split(':').map(Number);

      const startMinutes = startHour * 60 + startMin;
      const endMinutes = endHour * 60 + endMin;

      const duration = endMinutes - startMinutes;
      if (duration > 0) {
        setFormData((prev) => ({
          ...prev,
          duration,
        }));
      }
    }
  };

  const handleSave = () => {
    if (!user || !formData.title || !formData.startTime) {
      console.error('Missing required fields:', {
        user: !!user,
        title: formData.title,
        startTime: formData.startTime,
      });
      return;
    }

    // If no end time provided, assume 30 minutes duration
    let endTime = formData.endTime;
    if (!endTime && formData.startTime) {
      const [hours, minutes] = formData.startTime.split(':').map(Number);
      const startMinutes = hours * 60 + minutes;
      const endMinutes = startMinutes + 30; // Default 30 minutes
      const endHours = Math.floor(endMinutes / 60);
      const endMins = endMinutes % 60;
      endTime = `${endHours.toString().padStart(2, '0')}:${endMins
        .toString()
        .padStart(2, '0')}`;
    }

    const scheduleData: SchedulesProps = {
      id: schedule?.id,
      userId: user.uid,
      date: selectedDate,
      title: formData.title,
      startTime: formData.startTime,
      endTime: endTime,
      objective: formData.objective,
      duration: formData.duration || 30,
      status: formData.status || 'pending',
      priority: formData.priority || 'medium',
      reminder: formData.reminder,
      repeat: formData.repeat || 'none',
      autoGenerated: formData.autoGenerated || false,
      colorCode: formData.colorCode || '#E3F2FD',
      createdAt: schedule?.createdAt || new Date(),
      updatedAt: new Date(),
    };

    console.log('Saving schedule data:', scheduleData);
    onSave(scheduleData);
    onClose();
  };

  const handleDelete = () => {
    if (schedule?.id && onDelete) {
      onDelete(schedule.id);
      onClose();
    }
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="sm"
      fullWidth
      fullScreen={isMobile}
      PaperProps={{
        sx: {
          backgroundColor: theme?.mode === 'dark' ? '#1e293b' : '#ffffff',
          color: theme?.mode === 'dark' ? '#f1f5f9' : '#0f172a',
        },
      }}
    >
      <DialogTitle
        sx={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}
      >
        <Typography variant="h6" component="div" sx={{ fontWeight: 600 }}>
          {schedule ? 'Edit Schedule' : 'Create Schedule'}
        </Typography>
        <IconButton onClick={onClose} size="small">
          <CloseIcon />
        </IconButton>
      </DialogTitle>

      <DialogContent sx={{ pt: 2 }}>
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
          {/* Title - Most Important */}
          <TextField
            inputRef={titleInputRef}
            fullWidth
            label="Title *"
            value={formData.title}
            onChange={(e) => handleInputChange('title', e.target.value)}
            required
            variant="outlined"
            size="medium"
            sx={{
              '& .MuiInputLabel-root': {
                fontSize: '1.1rem',
                fontWeight: 600,
              },
              '& .MuiOutlinedInput-input': {
                fontSize: '1.1rem',
              },
            }}
            placeholder="What are you planning to do?"
          />

          {/* Date - Customizable */}
          <Box>
            <Typography
              variant="subtitle2"
              sx={{ mb: 1, fontWeight: 600, color: 'primary.main' }}
            >
              📅 Schedule Date
            </Typography>
            <TextField
              type="date"
              value={selectedDate}
              onChange={(e) => {
                if (onDateChange) {
                  onDateChange(e.target.value);
                }
              }}
              variant="outlined"
              size="medium"
              fullWidth
              InputLabelProps={{ shrink: true }}
              sx={{
                '& .MuiOutlinedInput-root': {
                  backgroundColor:
                    theme?.mode === 'dark' ? '#1e40af' : '#dbeafe',
                  border: '2px solid',
                  borderColor: 'primary.main',
                  '&:hover': {
                    backgroundColor:
                      theme?.mode === 'dark' ? '#1e40af' : '#dbeafe',
                  },
                  '&.Mui-focused': {
                    backgroundColor:
                      theme?.mode === 'dark' ? '#1e40af' : '#dbeafe',
                  },
                },
                '& .MuiInputBase-input': {
                  textAlign: 'center',
                  fontWeight: 600,
                  color: 'primary.main',
                  fontSize: '1.1rem',
                },
              }}
              helperText={new Date(selectedDate).toLocaleDateString('en-US', {
                weekday: 'long',
                year: 'numeric',
                month: 'long',
                day: 'numeric',
              })}
            />
            <Stack direction="row" spacing={1} mt={1.5} flexWrap="wrap">
              {[
                { label: 'Tomorrow', value: 'tomorrow' },
                { label: 'After Tomorrow', value: 'afterTomorrow' },
                { label: 'End of Week', value: 'endOfWeek' },
              ].map((item) => (
                <Button
                  key={item.value}
                  variant="outlined"
                  size="small"
                  onClick={() => handleQuickDate(item.value as 'tomorrow' | 'afterTomorrow' | 'endOfWeek')}
                  sx={{
                    borderRadius: '20px',
                    textTransform: 'none',
                    fontSize: '0.75rem',
                    px: 1.5,
                    py: 0.5,
                    borderColor: theme?.mode === 'dark' ? '#334155' : '#e2e8f0',
                    color: theme?.mode === 'dark' ? '#94a3b8' : '#64748b',
                    '&:hover': {
                      borderColor: 'primary.main',
                      color: 'primary.main',
                      bgcolor: 'transparent',
                    },
                  }}
                >
                  {item.label}
                </Button>
              ))}
            </Stack>
          </Box>

          {/* Compact Time Selection UI */}
          <Box
            component={motion.div}
            initial={{ opacity: 0, y: 5 }}
            animate={{ opacity: 1, y: 0 }}
            sx={{
              p: 1.5,
              borderRadius: 3,
              bgcolor: theme?.mode === 'dark' ? 'rgba(30, 41, 59, 0.2)' : 'rgba(241, 245, 249, 0.3)',
              border: `1px dashed ${muiTheme.palette.divider}`,
            }}
          >
            <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}>
              <Box sx={{ flex: 1 }}>
                <TextField
                  label="Start Time *"
                  type="time"
                  value={formData.startTime}
                  onChange={(e) => {
                    handleInputChange('startTime', e.target.value);
                    if (formData.endTime) {
                      handleDurationChange(e.target.value, formData.endTime);
                    }
                  }}
                  required
                  variant="outlined"
                  size="small"
                  fullWidth
                  InputLabelProps={{ shrink: true }}
                  sx={timeFieldStyle}
                />
                <Stack direction="row" spacing={0.5} mt={1} flexWrap="wrap" useFlexGap>
                  {dynamicQuickTimes.map((time) => (
                    <Button
                      key={time}
                      variant="text"
                      size="small"
                      onClick={() => handleInputChange('startTime', time)}
                      sx={quickTimeBtnStyle}
                    >
                      {time}
                    </Button>
                  ))}
                </Stack>
              </Box>

              <Box sx={{ flex: 1 }}>
                <TextField
                  label="End Time"
                  type="time"
                  value={formData.endTime}
                  onChange={(e) => {
                    handleInputChange('endTime', e.target.value);
                    if (formData.startTime) {
                      handleDurationChange(formData.startTime, e.target.value);
                    }
                  }}
                  variant="outlined"
                  size="small"
                  fullWidth
                  InputLabelProps={{ shrink: true }}
                  sx={timeFieldStyle}
                  FormHelperTextProps={{ sx: { m: 0, mt: 0.5, fontSize: '0.65rem' } }}
                  helperText={
                    formData.duration
                      ? `⏱️ ${formData.duration}m`
                      : ''
                  }
                />
                <Stack direction="row" spacing={0.5} mt={1} flexWrap="wrap" useFlexGap>
                  {[15, 30, 60, 120].map((mins) => (
                    <Button
                      key={mins}
                      variant="text"
                      size="small"
                      disabled={!formData.startTime}
                      onClick={() => applyDuration(mins)}
                      sx={quickTimeBtnStyle}
                    >
                      +{mins >= 60 ? `${mins / 60}h` : `${mins}m`}
                    </Button>
                  ))}
                </Stack>
              </Box>
            </Stack>
          </Box>

          {/* Objective */}
          <TextField
            fullWidth
            label="Objective (Optional)"
            value={formData.objective}
            onChange={(e) => handleInputChange('objective', e.target.value)}
            variant="outlined"
            size="medium"
            placeholder="What's the goal or purpose?"
            helperText="💡 Adding an objective helps you stay focused"
          />

          {/* Advanced Options - Collapsible Section */}
          <Box>
            <Button
              onClick={() => setAdvancedOpen(!advancedOpen)}
              fullWidth
              startIcon={advancedOpen ? <ExpandLessIcon /> : <ExpandMoreIcon />}
              sx={{
                justifyContent: 'flex-start',
                textTransform: 'none',
                fontSize: '0.95rem',
                fontWeight: 600,
                color: theme?.mode === 'dark' ? '#cbd5e1' : '#475569',
                mb: 2,
              }}
            >
              {advancedOpen ? 'Hide' : 'Show'} Advanced Options
            </Button>

            <Collapse in={advancedOpen} timeout="auto" unmountOnExit>
              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
                {/* Priority */}
                <FormControl fullWidth size="medium">
                  <InputLabel>Priority</InputLabel>
                  <Select
                    value={formData.priority}
                    onChange={(e) =>
                      handleInputChange('priority', e.target.value)
                    }
                    label="Priority"
                  >
                    {priorityOptions.map((option) => (
                      <MenuItem key={option.value} value={option.value}>
                        <Box display="flex" alignItems="center" gap={1}>
                          <Box
                            sx={{
                              width: 12,
                              height: 12,
                              borderRadius: '50%',
                              backgroundColor: option.color,
                            }}
                          />
                          {option.label}
                        </Box>
                      </MenuItem>
                    ))}
                  </Select>
                </FormControl>

                {/* Reminder Settings */}
                <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
                  <TextField
                    label="Remind me"
                    type="number"
                    value={formData.reminder?.before || 10}
                    onChange={(e) =>
                      handleInputChange('reminder', {
                        ...formData.reminder,
                        before: parseInt(e.target.value) || 10,
                      })
                    }
                    variant="outlined"
                    size="medium"
                    sx={{ flex: 1, minWidth: '120px' }}
                    helperText="minutes before"
                  />

                  <FormControl
                    size="medium"
                    sx={{ flex: 1, minWidth: '150px' }}
                  >
                    <InputLabel>Alert via</InputLabel>
                    <Select
                      value={formData.reminder?.method || 'notification'}
                      onChange={(e) =>
                        handleInputChange('reminder', {
                          ...formData.reminder,
                          method: e.target.value,
                        })
                      }
                      label="Alert via"
                    >
                      {reminderMethods.map((method) => (
                        <MenuItem key={method.value} value={method.value}>
                          {method.label}
                        </MenuItem>
                      ))}
                    </Select>
                  </FormControl>
                </Box>

                {/* Repeat */}
                <FormControl fullWidth size="medium">
                  <InputLabel>Repeat</InputLabel>
                  <Select
                    value={formData.repeat}
                    onChange={(e) =>
                      handleInputChange('repeat', e.target.value)
                    }
                    label="Repeat"
                  >
                    {repeatOptions.map((option) => (
                      <MenuItem key={option.value} value={option.value}>
                        {option.label}
                      </MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Box>
            </Collapse>
          </Box>
        </Box>
      </DialogContent>

      <DialogActions sx={{ p: 3, gap: 1, flexWrap: 'wrap' }}>
        {schedule && onDelete && (
          <Button
            onClick={handleDelete}
            color="error"
            variant="outlined"
            size="large"
            startIcon={<DeleteIcon />}
            sx={{ mr: 'auto' }}
          >
            <Box sx={{ display: { xs: 'none', sm: 'inline' } }}>Delete</Box>
          </Button>
        )}
        <Button onClick={onClose} variant="outlined" size="large">
          Cancel
        </Button>
        <Button
          onClick={handleSave}
          variant="contained"
          disabled={!formData.title || !formData.startTime}
          size="large"
          sx={{
            backgroundColor: theme?.mode === 'dark' ? '#3b82f6' : '#2563eb',
            '&:hover': {
              backgroundColor: theme?.mode === 'dark' ? '#2563eb' : '#1d4ed8',
            },
            px: { xs: 2, sm: 4 },
          }}
        >
          {schedule ? 'Update' : 'Create'}
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default SchedulesModal;
