import type { Metadata } from 'next';
import { Inter, Roboto } from 'next/font/google';
import './globals.css';
import ClientThemeProvider from './components/global/ClientThemeProvider';
import Navbar from './components/global/Navbar';
import EmotionRegistry from './emotionRegistry';
import AppBarTop from './components/global/AppBarTop';
// Google Fonts
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // You can customize this
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  themeColor: '#2563eb',
  icons: {
    icon: '/icons/icon-192x192.png',
    apple: '/icons/icon-192x192.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`pb-30 ${inter.variable} ${roboto.variable} antialiased`}
      >
        <EmotionRegistry>
          <ClientThemeProvider>
            <AppBarTop />
            <Navbar />
            {children}
          </ClientThemeProvider>
        </EmotionRegistry>
      </body>
    </html>
  );
}
